# SPDX-License-Identifier: AGPL-3.0-or-later
# Derivato dall'add-on Home Assistant di Homeway.io (https://github.com/homewayio/AddOn),
# a sua volta derivato da OctoEverywhere. Vedi NOTICE.md.

# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Proto

class DataCompression(object):
    None_ = 0
    Brotli = 1
    Zlib = 2
    ZStandard = 3
