# SPDX-License-Identifier: AGPL-3.0-or-later
# Derivato dall'add-on Home Assistant di Homeway.io (https://github.com/homewayio/AddOn),
# a sua volta derivato da OctoEverywhere. Vedi NOTICE.md.

# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Proto

class MessageContext(object):
    NONE = 0
    HandshakeSyn = 1
    HandshakeAck = 2
    WebStreamMsg = 3
    Summon = 4
